"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['gtask_notifier.py']
DATA_FILES = []
OPTIONS = {
    'py2app': {
        'iconfile': 'coconut.icns',  # Lokasi ikon kustom
        'argv_emulation': True,
        'plist': {
            'LSUIElement': True,
            'CFBundleName': 'Google Task Reminder',  # Nama aplikasi
            'CFBundleShortVersionString': '1.0',  # Versi aplikasi
            'CFBundleGetInfoString': 'Google Task Reminder 1.0',  # Info versi aplikasi
            'CFBundleExecutable': 'Google Task Reminder'  # Nama eksekutor aplikasi
        },
        'packages': ['rumps']
    }
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options=OPTIONS,
    setup_requires=['py2app'],
)
